version: '3.8'

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .  # this also sets the folder in which dockerfile(image) will be built
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./ngnix/ngnix.conf:/etc/ngnix/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # ports:  # if only we need to access PHP container using our local machine (PHP exposes 9000:see github Dockerfile of official php dockerhub image)
    #   - '3000:9000'
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]  # this entrypoint gets created or overridden in the dockerfile (image)
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html