version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://thisisleo7:gcz3vJ0VCdVOKYF5@cluster0.mm2msjs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      AUTH_API_ADDRESSS: 'auth:3000'