apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 80  # on which we want to expose the pod
      targetPort: 3000  # port my container exposes
